ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'PROVISIONED';
ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'LICENSE_ASSIGNED';
ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'ACTIVATED';
ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'RUNNING';
ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'DELETED';
ALTER TYPE "RestaurantStatus" ADD VALUE IF NOT EXISTS 'PURGED';
